### ISSUE TITLE
Using the restocking upgrade with the builder's wand from EU2 deletes items

### ISSUE THREAD

**Issue by Mizuna737** [gr8pefish/IronBackpacks#160] opened 2017-03-22 17:32 UTC
#### Issue Description:
Exactly what it says in the title. As far as I can tell there isn't a set number of items deleted, just 'some'.

#### What happens:
When using the builder's wand from Extra Utilities 2 to place dirt, some times the dirt is restocked, other times it isn't. When it is, more dirt is deleted from the backpack than was placed (by far).

#### What you expected to happen:
Place 9 dirt, 9 dirt used.

#### Steps to reproduce (important):

1. Equip a backpack with a restocking upgrade and filter a block to be restocked.
2. Having that block in your inventory, right click with the builder's wand to place the block.

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.23
- Minecraft: 1.10.2
- Forge: 8.0.99.99
- Other Conflicting Mods (may be irrelevant to your issue): Extra Utilities 2 version 1.3.3

**Comment by Hazerd** [comment] 2017-03-24 01:06
Duplicate of #130, which was supposedly resolved. Strange this popped up again.

**Comment by gr8pefish** [comment] 2017-03-24 03:10
Yes, strange indeed. I explicitly removed compatibility from ExUtils to avoid this; perhaps RWTema changed his code since that last issue. I'll investigate soon and try to fix this.

**Comment by gr8pefish** [comment] 2017-03-29 15:45
Ah, he changed the mod ID from "ExtraUtils2" to "extrautils2" (lowercase), so my mod compatibility code wasn't registering that ExU was even present. Changing my own code that looks for ExU to lowercase should fix the issue.

**Closed as completed** 2017-03-29 16:00 UTC
Labels: bug, investigating
