### ISSUE TITLE
Not so phantom phantom items.

### ISSUE THREAD

**Issue by sdpragequit** [gr8pefish/IronBackpacks#119] opened 2016-12-10 04:10 UTC
Issue Description:
Hey, I came upon a bug/oversight concerning the "phantom" items in the Filter GUI (the one opened by shift+right clicking a backpack). The bug allows for item duplication. I'm using the FTB Direwolf20 modpack for minecraft 1.10.2 but im sure that the bug is not exclusive to this modpack.

Steps to reproduce:
1. Place Item X in any of the Filter Upgrade slots (https://puu.sh/sKgLo/3e893c644f.png).
2. Hover over Item X and scroll up on the mouswheel (https://puu.sh/sKgPW/b19bbefd1f.png).
3. ...
4. Profit!

Affected Versions:

- IronBackpacks: 2.2.13
- Minecraft: 1.10.2
- Forge: 12.18.2.2124

PS: This works with the Basic Filter, Compression and Mining Filter Upgrade (I have not tested others, however I assume, that this bug is replicable with any of the filter type upgrades).
PPS: Doing the reverse (Putting an item in the filter by scrolling up) results in a "loss" of the item, as it ends up as the "phantom" item.

**Comment by TehNut** [comment] 2016-12-10 04:13
Is Item Scroller in DW20? That might be the cause. Or Inventory Sorter.

**Comment by Hazerd** [comment] 2016-12-10 10:48
Possible duplicate of #104 which was already fixed.
Try updating your IronBackpacks if possible. You're currently 6 versions behind.

**Comment by gr8pefish** [comment] 2016-12-10 14:50
Thanks for the bug report!

Yes, try updating as per Hazerdous' suggestion, and then update us with a reply here on if that fixes it or not.

**Comment by sdpragequit** [comment] 2016-12-10 17:13
@TehNut Inventory Sorter is in the Pack (Version 0.10.0+42)

I updated Iron backpacks to 2.2.19 and indeed the problem is already fixed 50%.  (Forge: 12.18.2.2171)

It is no longer possible to use the mousewheel to take an item out of the filter GUI, however it is still possible to put an item into the GUI from your inventory by using the scroll function. This results in a phantom item in the filter, at the cost of losing the item from your inventory (I should not have tried this with my Hammer)

1. https://puu.sh/sKKPv/33063c90c3.png
2. https://puu.sh/sKKQj/7b22da2567.png

Thanks for the quick replies! And keep up the good work, it's a great mod.

**Comment by gr8pefish** [comment] 2016-12-10 17:16
Alright, I'll check it out more! I'm busy with finals coming up in the next couple days, but I'll look at it as soon as I am reasonably able to.

**Comment by sdpragequit** [comment] 2016-12-10 17:16
Thanks, and Good Luck!

**Closed as completed** 2016-12-15 00:07 UTC
Labels: bug, investigating, fixed for next version, mod interaction
