### ISSUE TITLE
Block Duplication Glitch

### ISSUE THREAD

**Issue by mookooy** [gr8pefish/IronBackpacks#106] opened 2016-11-23 20:58 UTC
#### Issue Description:
block duplication glitch

#### What happens:
When you place blocks after you run out you can still place seemingly forever and if you pickup another of that block type all the blocks you place are still in the world but reappear in your inventory   

#### Affected Versions:

- IronBackpacks: 1.10.2-2.2.17
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2076

this a great mod and I want to play survival with It but this breaks the game

**Comment by TehNut** [comment] 2016-11-23 21:23
Do the blocks persist after reloading the world?

**Comment by mookooy** [comment] 2016-11-23 21:54
yes they do

**Comment by Hazerd** [comment] 2016-11-24 02:55
This is due to the forge version, duplicate of #99

**Closed as completed** 2016-11-24 02:56 UTC

**Comment by mookooy** [comment] 2016-11-24 03:56
No it isn't I uninstalled the Mod and It stopped the glitch I reinstalled and the glitch came Back

**Comment by TehNut** [comment] 2016-11-24 04:05
Update Forge.

**Comment by mookooy** [comment] 2016-11-24 04:41
sorry that fixed it
