### ISSUE TITLE
Dupe issue 

### ISSUE THREAD

**Issue by JoeSGT** [gr8pefish/IronBackpacks#204] opened 2017-11-21 22:09 UTC
Note: Delete the following 2 lines when you submit the issue. 
* If this bug occurs in a modpack, please try first reporting it to the modpack author. Barring that, please narrow down exactly what other mod(s) are responsible for the issue. 
* If this is a feature request, this template does not apply to you. Just delete everything and write what you need.

#### Issue Description:
you have to drop the backpack then right click and you will be able to have the GUI open
and the backpack on the floor, in then gui backpack take the items
then pickup the backpack and right click it you will be able to take those items as well

#### What happens:
Essentially drop the backpack while fast right click you will have gui open and backpack on the floor
being able to drop 

#### What you expected to happen:
Dupe items 

#### Steps to reproduce (important):

1. first put items in the backpack
2. drop the backpack while you right click at the same time 
3.  you will have the gui open take the items out and pickup backpack that was drop and take those items out
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 3.0.1-2
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.0.2550
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by gr8pefish** [comment] 2017-11-22 02:38
Duplicate of #176 for reference, which was the same bug in 1.10.

We will look into it. Thank you for the bug report.

**Comment by DumbSlayer** [comment] 2017-12-12 15:40
omg thx man ima use this on servers like a shit ton of servers

**Comment by DumbSlayer** [comment] 2017-12-12 21:29
y get rid of my comment i was just saying i was gonna use it on a shit ton of servers

**Comment by TehNut** [comment] 2017-12-15 02:58
https://github.com/gr8pefish/IronBackpacks/commit/2f3f0b1f6929d865384b85f517c6239a4e7a1adb

**Closed as completed** 2018-01-16 18:10 UTC
Labels: bug, fixed for next version, 1.12
