### ISSUE TITLE
Ghost Block Placement with Quick Deposit Upgrade

### ISSUE THREAD

**Issue by Darkosto** [gr8pefish/IronBackpacks#129] opened 2016-12-15 21:20 UTC
#### Issue Description:
When having an iron backpack on with the quick deposit upgrade installed, having some items in your backpack,  it won't allow you to place a block on a block with an inventory (ie chest). It places a ghost item in your hotbar like a desync.

#### What happens:

https://www.dropbox.com/s/j2iv5qd4yjvyjrg/2016-12-15_21-10-00.mp4?dl=0

#### Steps to reproduce (important):

1. Have backpack with quick deposit upgrade
2. Have items in the backpack
3. Place block on another block with an inventory
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.19
- Minecraft: 1.10.2
- Forge: 2185

**Comment by gr8pefish** [comment] 2016-12-15 21:22
Update to 2.2.20, it should be fixed there.

Duplicate of #121

**Closed as completed by gr8pefish** 2016-12-15 21:22 UTC

**Comment by Darkosto** [comment] 2016-12-15 21:24
Ya know, I almost looked to see if that was fixed but decided to put the issue in anyways. I'll get the FTB tester team up to date. Thanks :)

**Comment by gr8pefish** [comment] 2016-12-15 21:25
No worries, it takes me all of 30 seconds to close it. I would *much* rather you err on the side of reporting too much than too little :)
