### ISSUE TITLE
crash on death

### ISSUE THREAD

**Issue by LlubNek** [gr8pefish/IronBackpacks#48] opened 2016-01-28 06:09 UTC
IronBackpacks-1.8.9-2.0.0.jar caused a crash when I was killed by a Fallen Knight (EnderZoo-1.8.9-1.1.2.jar) on a ladder.
I did not have a backpack in my inventory.

Here's the crash report:
http://pastebin.com/Hzz3vt30

**Comment by TehNut** [comment] 2016-01-28 22:01
Dupe of #47 (different cause, same issue)

**Closed as completed by TehNut** 2016-01-28 22:01 UTC
