### ISSUE TITLE
Fix Lost Backpacks Still Picking Up Items

### ISSUE THREAD

**Issue by NicoHana** [gr8pefish/IronBackpacks#187] opened 2017-08-14 17:12 UTC
#### Issue Description:
One of two diamond backpacks disappearing on falling out of the world, and mined items vanishing/being deleted thereafter.

#### What happens:
Cobblestone, nether quartz, lapis, redstone, numerous ores (minus mined inferium essence) are presumably deleted as they do not appear in ANY inventory, freshly mined or otherwise.

#### What you expected to happen:
The new mined items to be picked up in the new backpack or failing that, the older remaining   backpack/main character inventory.

#### Steps to reproduce (important):

1. Have packs in hotbar (two +Storage diamond with compression and mining filter upgrades both set to cobblestone), and go mining in The Beneath.
2. Fall out of the world on exiting The Beneath with keep inventory set to true.
3. Make a new pack with the same upgrades.
4. Enter and mine anything from The Beneath again.

Addendum: Between my query on Curseforge and now, I trashed any previous backpacks, and created one new leather backpack with NO upgrades at all. All cobble and ores still being vanishing/being deleted.
____
#### Affected Versions (Do *not* use "latest"):

- Sky Factory 3: 3.0.13
- IronBackpacks: 1.10.2-2.2.27
- Minecraft: 1.10.2
- Forge: 12.18.3.2316

**Comment by gr8pefish** [comment] 2017-08-14 17:25
To clarify, did any of this occur with an _equipped_ backpack, or was it all with backpacks just in your normal inventory/hotbar? And are there any mods in the modpack that may conflict/cause odd errors with items saving post death?

**Comment by NicoHana** [comment] 2017-08-14 17:40
Damn it, I knew I forgot something, sorry!

Question 1: The packs have only never been in my hotbar/inventory.
 - Related addendum: Even with no backpacks in my hotbar/inventory, items are still deleted.

Question 2: Not had problems with any other mods, or items being lost with past deaths, so I wouldn't notice.

**Comment by gr8pefish** [comment] 2017-08-14 19:17
> only never been in my hotbar/inventory

I'm going to assume you mean "only **ever** been" :P 

This is super strange. Can you look at your player.dat file and post a screenshot of it (or paste a link to it here), so that I can see if a backpack is in your inventory?

**Comment by NicoHana** [comment] 2017-08-15 14:23
Yes, that is indeed what I meant. DERP.

If there is, it would be a plain leather one, and of course strange shit would happen to me. XD

FFS, finally got NBTExplorer to cooperate. Sorry for the delay

![screenshot 2017-08-15 15 17 20](https://user-images.githubusercontent.com/30985806/29319925-9595473c-81cd-11e7-9eee-0ed6a149c80f.png)
![screenshot 2017-08-15 15 17 04](https://user-images.githubusercontent.com/30985806/29319932-990e5552-81cd-11e7-8a73-67938db91dae.png)

**Comment by gr8pefish** [comment] 2017-08-15 20:43
Can you upload the file here so I can have access to it? Those screenshots don't quite show me what I need.

Also, what are the IDs of the backpacks in the modpack? You can do F3+H in-game and it will show detailed tooltips, including the IDs.

**Comment by NicoHana** [comment] 2017-08-15 20:47
Just to be sure, its the NicoHana.dat yeah? XD

I don't usually delve this deep into the 'background' files of minecraft xD

**Comment by gr8pefish** [comment] 2017-08-15 20:52
Yeah, that should be it.

**Comment by NicoHana** [comment] 2017-08-23 21:45
I think this is the right one, finally. *sigh*
[NicoHana.dat.zip](https://github.com/gr8pefish/IronBackpacks/files/1246813/NicoHana.dat.zip)

And you wouldn't happen to know the mac version of that F3+H?

**Comment by gr8pefish** [comment] 2018-01-07 22:39
Sorry for the lack of a response; I had some serious family stuff come up. Were you ever able to determine the cause of this or fix it or even just avoid it? It's so niche I may end up simply closing the issue.

**Closed as completed** 2018-01-21 00:38 UTC
Labels: can't replicate, waiting on response
