### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by blockbreaker1361** [gr8pefish/IronBackpacks#35] opened 2015-12-15 18:58 UTC
I am using Iron Backpack version 1.1.1 on MC 1.7.10 and when you turn your character to the left or right, you can see the backpack in your FOV. Included is a pic explaining further.
http://imgur.com/I3JYm5g

**Comment by gr8pefish** [comment] 2015-12-15 19:08
Is it only when you spin rapidly to either side? Because, if so, it is working as intended (since, in real life, if you turn quickly the backpack takes a moment to "catch up" and so you see it for a moment before it goes back behind you). It should go away soon after you stop spinning though.

If that isn't the case though:
- What is your field of vision setting at?
- What version of IB are you on? You provided one that doesn't exist. If you aren't on at least version 27/1.2.9 please update and let me know if it happens again.

**Comment by blockbreaker1361** [comment] 2015-12-16 10:42
Sorry. I put version of a different mod here. I was using 1.2.10. My FOV is set to normal. I will download the latest version today, which is 1.2.11 and let you know.

**Comment by gr8pefish** [comment] 2015-12-16 10:44
That won't change anything, I didn't mess with the rendering in the last version.

Can you answer this question please:

> Is it only when you spin rapidly to either side?

**Comment by gr8pefish** [comment] 2016-01-07 19:54
Alright, seems to be no other issues from other people, so I am closing this, I think it is working as intended.

**Closed as completed by gr8pefish** 2016-01-07 19:54 UTC
Labels: bug, minor, need more info
