### ISSUE TITLE
Crashing when first naming a diamond backpack 1.10.2

### ISSUE THREAD

**Issue by falizure** [gr8pefish/IronBackpacks#179] opened 2017-07-04 05:00 UTC
When a player specific player attempts to name a diamond backpack for the first time on the server it caused them to crash, the same player had a identical crash on another server with only a few similar mods, namely forge and tinkers construct (probably different versions even) however it only seams to have happened to that 1 player so far, i am only aware of that 1 person. i have no received a crash report from them to go into more specifics but it could be something to look into, if it occurs more or i do get a report ill try and update the post.
____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.27
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2316
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by TehNut** [comment] 2017-07-04 05:01
We can't do anything without a log.

**Comment by falizure** [comment] 2017-07-10 20:35
I apologize for not responding sooner, i was able to get a crash report from the player today after they joined yet another 1 of our servers and crashed yet again from iron backpacks, ill post the crash report.
[crash-2017-07-10_15.36.59-client.txt](https://github.com/gr8pefish/IronBackpacks/files/1136997/crash-2017-07-10_15.36.59-client.txt)

**Comment by TehNut** [comment] 2017-07-10 20:38
Dupe of #178

**Closed as completed by TehNut** 2017-07-10 20:38 UTC
