### ISSUE TITLE
Iron Backpacks Inventory Dupe

### ISSUE THREAD

**Issue by Otisnfur** [gr8pefish/IronBackpacks#215] opened 2018-01-20 16:33 UTC
#### Issue Description:

Throwing a backpack (of any tier) on the ground whilst quickly opening it from your inventory allows you to pull _items_ out of the inventory of the backpack. Picking the backpack up off the ground shows the items still inside of the bag, allowing you to duplicate items that were inside.
https://www.youtube.com/watch?v=0_rxk0yegOw&feature=youtu.be

#### What happens:

Opening a backpack while throwing it allows you to dupe.

#### What you expected to happen:

To not be able to open the backpack/take items out and dupe them.

#### Steps to reproduce (important):

1. Get a backpack
2. Put items in the backpack
3. Throw the backpack with Q (Or your drop button)
4. Very quickly while hitting Q open your backpack
5. Pull out the items
6. Pick up the bag
7. Have twice the amount of items

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.31.jar
- Minecraft: 1.10.2
- Forge: 12.18.3.2477
- Other Conflicting Mods (may be irrelevant to your issue): It's the Sky Factory 3 Modpack

**Comment by Otisnfur** [comment] 2018-01-20 16:37
This also effects Minecraft version 1.12.2 Forge 14.23.1.2573 IB 1.12.2-3.0.2.3

**Comment by TehNut** [comment] 2018-01-20 21:09
The duped items in 1.12 are client only as noted in my commit message fixing it the last time it was reported.

**Comment by Otisnfur** [comment] 2018-01-20 23:38
Ah, thank you. I looked a bit but did not see a thread similar to this one. What about the duped items in 1.10?

**Comment by TehNut** [comment] 2018-01-20 23:49
I don't know, I don't touch 1.10.

**Comment by gr8pefish** [comment] 2018-01-20 23:51
Should be fixed in 1.10. See #176. Let me know if it isn't and I'll fix it.

**Closed as completed** 2018-01-21 01:51 UTC
Labels: bug, 1.10

**Comment by mkrtes** [comment] 2018-02-14 19:51
So, ver. IronBackpacks-1.10.2-2.2.33 - is dupe

**Comment by TehNut** [comment] 2018-02-14 20:06
Then go to the 1.10 issue.

**Comment by CDAGaming** [comment] 2018-02-14 21:05
There is also another Dupe in 1.12.2, see my Issue for that one, #223

**Comment by CDAGaming** [comment] 2018-02-14 21:06
(Will Edit #223 to state that the dupe I discovered, is also Server Side, as I had to pull it from my Pack due to the Dupe)

**Comment by TehNut** [comment] 2018-02-14 22:29
Well there is no need to mention that here as the issue is already open...
